//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpajamHonsen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HVCLog
    {
        public string LogID { get; set; }
        public string SpotID { get; set; }
        public string Language { get; set; }
        public int Expression { get; set; }
        public int Age { get; set; }
        public string Sex { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    }
}
