//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpajamHonsen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tweet
    {
        public string TweetID { get; set; }
        public string SpotID { get; set; }
        public string TweetTextjp { get; set; }
        public string TweetTextcn { get; set; }
        public string TweetTexten { get; set; }
        public string TweetURL { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    }
}
