//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpajamMadobenWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudioCommentary
    {
        public string AudioCommentaryKey { get; set; }
        public string AudioCommentaryTitle { get; set; }
        public string SpotKey { get; set; }
        public Nullable<long> SortID { get; set; }
        public string FileID { get; set; }
        public string AudioCommentaryResultOriginal { get; set; }
        public string AudioCommentaryResultConversion { get; set; }
        public string SpeechSynthesisFileID { get; set; }
        public string RegisteredUserID { get; set; }
        public System.DateTime RegisteredDateTime { get; set; }
    }
}
